# Paquetes separados por espacios. Este archivo se carga como Bash.
BASE_PACKAGES="sudo ca-certificates curl wget git gnupg lsb-release apt-transport-https unzip zip rsync htop"
FIREWALL_PACKAGES="ufw"
AUTO_UPDATE_PACKAGES="unattended-upgrades apt-listchanges"
SECURITY_HARDENING_PACKAGES="apparmor apparmor-utils logwatch"
SSH_HARDENING_PACKAGES="fail2ban"
CLI_PACKAGES="nano"
XFCE_PACKAGES="xfce4 xfce4-goodies lightdm network-manager-gnome"
LXQT_PACKAGES="lxqt-core lightdm network-manager-gnome qterminal"
PROFILE_MEDIA_PACKAGES="fastfetch"
PROFILE_ALTA_PACKAGES="fastfetch nala"
PROFILE_ULTRA_PACKAGES="fastfetch nala preload"
VMWARE_CLI_PACKAGES="open-vm-tools"
VMWARE_GUI_PACKAGES="open-vm-tools open-vm-tools-desktop"
NVIDIA_BASE_PACKAGES="nvidia-driver firmware-misc-nonfree"
NVIDIA_GUI_PACKAGES="nvidia-driver firmware-misc-nonfree nvidia-settings"
FLATPAK_APPS="md.obsidian.Obsidian org.videolan.VLC com.bitwarden.desktop org.remmina.Remmina"
DEBLOAT_CANDIDATES_COMMON="vim vim-tiny vim-common vim-runtime neovim libreoffice thunderbird rhythmbox shotwell simple-scan cheese"
DEBLOAT_CANDIDATES_XFCE="xfce4-notes-plugin mousepad xfce4-terminal xfce4-goodies"
DEBLOAT_CANDIDATES_LXQT="featherpad screengrab qterminal lximage-qt qpdfview qalculate-gtk"
