# Paquetes separados por espacios. Este archivo se carga como Bash.
BASE_PACKAGES="sudo ca-certificates curl wget git gnupg lsb-release apt-transport-https unzip zip rsync htop"
FIREWALL_PACKAGES="ufw"
AUTO_UPDATE_PACKAGES="unattended-upgrades apt-listchanges"
SECURITY_HARDENING_PACKAGES="apparmor apparmor-utils logwatch"
SSH_HARDENING_PACKAGES="fail2ban"
CLI_PACKAGES="vim-tiny tmux"
XFCE_PACKAGES="xfce4 xfce4-goodies lightdm network-manager-gnome"
LXQT_PACKAGES="lxqt-core lightdm network-manager-gnome qterminal"
PROFILE_MEDIA_PACKAGES="fastfetch"
PROFILE_ALTA_PACKAGES="fastfetch nala"
PROFILE_ULTRA_PACKAGES="fastfetch nala preload"
FLATPAK_APPS="org.videolan.VLC md.obsidian.Obsidian com.bitwarden.desktop org.remmina.Remmina"
